version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'

  nginx:
    build:
      dockerfile: nginx/Dockerfile.dev
      context: nginx
    restart: always
    ports:
      - '3001:80'
    depends_on:
      - api
      - client

  api:
    build:
      dockerfile: server/Dockerfile.dev
      context: server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432

  client:
    stdin_open: true
    build:
      dockerfile: client/Dockerfile.dev
      context: client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: worker/Dockerfile.dev
      context: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
