sudo: required
language: generic
services:
  - docker

before_install:
  - cd ./complex
  - docker build -f ./client/Dockerfile.dev -t bifidokk/docker-course-client-test ./client

script:
  - docker run -e CI=true bifidokk/docker-course-client-test npm test

after_success:
  - docker build -t bifidokk/multi-client ./client
  - docker build -t bifidokk/multi-nginx ./nginx
  - docker build -t bifidokk/multi-server ./server
  - docker build -t bifidokk/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bifidokk/multi-client
  - docker push bifidokk/multi-nginx
  - docker push bifidokk/multi-server
  - docker push bifidokk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-096541367626'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY